INSERT INTO DEVICE (DEVICE_NAME) VALUES ('iPhone1');
INSERT INTO DEVICE (DEVICE_NAME) VALUES ('iPhone2');
INSERT INTO DEVICE (DEVICE_NAME) VALUES ('iPhone3');
INSERT INTO DEVICE (DEVICE_NAME) VALUES ('Samsung1');
INSERT INTO DEVICE (DEVICE_NAME) VALUES ('Samsung2');
INSERT INTO DEVICE (DEVICE_NAME) VALUES ('Samsung3');
INSERT INTO USER (USER_NAME) VALUES ('user1');
INSERT INTO USER (USER_NAME) VALUES ('user2');
INSERT INTO USER (USER_NAME) VALUES ('user3');
INSERT INTO USER (USER_NAME) VALUES ('user4');
INSERT INTO USER (USER_NAME) VALUES ('user5');


